multiple compile error/warning/note fixes for linux (gcc)
novusengine/Engine pull request #3
Opened 2023-09-10 17:50 UTC by MellianStudios

2023-10-03 14:30 UTC, Pursche commented
For documentations sake, this is currently waiting on the AssetConverter to become public, it's stuck at not being able to load data because we have differences in path capitalization so our hashes don't match.

2023-11-10 23:01 UTC, NixAJ requested changes
Left comments for requested changes

2023-11-10 23:01 UTC, NixAJ commented on Source/ShaderCooker/ShaderCooker/Lexer/Lexer.h
> +#include <Base/Platform.h>
Base include should be below ShaderCooker includes

2023-11-10 23:20 UTC, NixAJ approved these changes

2023-11-10 23:20 UTC, merged